from abc import ABC, abstractmethod


class GenerativeModel(ABC):
    @abstractmethod
    def generate_photo(self, prompt: str) -> str:
        """
        Method must implement logic of generating a photo by prompt.
        Args:
            prompt: prompt for photo generating

        Returns:
            path to local photo generated by prompt
        """
        pass
